import { workflow, node, trigger, ifElse, expr, sticky } from '@n8n/workflow-sdk';
const startReview = trigger({type:'n8n-nodes-base.manualTrigger',version:1,config:{name:'Start Hunter Review',position:[0,300]},output:[{}]});
const compareSources = node({type:'n8n-nodes-base.httpRequest',version:4.5,config:{
name:'Compare Hunter Sources',position:[240,300],retryOnFail:false,
credentials:{httpHeaderAuth:{id:"855e3b47963acb18",name:"Hunter Review - Local Only"}},
parameters:{method:'POST',url:'http://hunter-review:8788/v1/reviews',authentication:'genericCredentialType',genericAuthType:'httpHeaderAuth',
sendBody:true,specifyBody:'json',jsonBody:expr('{{ { request_id: "n8n:" + $execution.id } }}'),
options:{timeout:10000,redirect:{redirect:{followRedirects:false}},response:{response:{responseFormat:'json'}}}}},output:[{schema_version:'1',mode:'review_only',status:'REVIEW_REQUIRED',publication_allowed:false,run_id:'sample-only',summary:{added:4,changed:0,removed:0,unchanged:0,total:4,held:4,candidate_records:4,forum_sections:0},records:[],removed:[]}]});
const validatePacket=node({type:'n8n-nodes-base.code',version:2,config:{name:'Validate Review Packet',position:[480,300],parameters:{mode:'runOnceForAllItems',language:'javaScript',jsCode:"const p = $input.first().json;\nif (p.schema_version !== \"1\" || p.mode !== \"review_only\" || p.status !== \"REVIEW_REQUIRED\" || p.publication_allowed !== false || !Array.isArray(p.records) || !Array.isArray(p.removed) || !p.run_id || !p.summary) throw new Error(\"Invalid review response: no publication or approval is permitted\");\nfor (const key of [\"total\",\"added\",\"changed\",\"removed\",\"unchanged\",\"held\",\"candidate_records\",\"forum_sections\"]) if (!Number.isSafeInteger(p.summary[key]) || p.summary[key] < 0) throw new Error(\"Invalid review counts\");\nif (p.summary.total !== p.records.length || p.summary.removed !== p.removed.length || p.summary.held !== p.summary.total || p.summary.added+p.summary.changed+p.summary.unchanged !== p.summary.total) throw new Error(\"Inconsistent review packet\");\nif (!p.records.every(r => r.status === \"HELD\" && Array.isArray(r.findings) && r.findings.length > 0)) throw new Error(\"Missing review holds\");\nreturn [{json:p}];"}},output:[{status:'REVIEW_REQUIRED',summary:{added:4,changed:0,removed:0},publication_allowed:false}]});
const hasChanges=ifElse({version:2.3,config:{name:'Source Changes?',position:[720,300],parameters:{conditions:{options:{caseSensitive:true,leftValue:'',typeValidation:'strict',version:2},conditions:[{leftValue:expr('{{ $json.summary.added + $json.summary.changed + $json.summary.removed }}'),rightValue:0,operator:{type:'number',operation:'gt'}}],combinator:'and'}}},output:[{status:'REVIEW_REQUIRED'}]});
const changedReport=node({type:'n8n-nodes-base.code',version:2,config:{name:'Review Changed Sources',position:[970,200],parameters:{mode:'runOnceForAllItems',language:'javaScript',jsCode:"const p = $input.first().json;\nconst changes = p.summary.added+p.summary.changed+p.summary.removed;\nconst lines = [\"# Hunter OS source review\", \"\", \"**REVIEW REQUIRED — no publication approved**\", \"\",\n  \"Run: \"+p.run_id, \"Observed: \"+p.created_at, \"\",\n  p.summary.total+\" items: \"+p.summary.candidate_records+\" candidate records and \"+p.summary.forum_sections+\" forum sections.\",\n  \"Added: \"+p.summary.added+\" · Changed: \"+p.summary.changed+\" · Removed: \"+p.summary.removed+\" · Unchanged: \"+p.summary.unchanged,\n  \"Held for review: \"+p.summary.held, \"\",\n  \"Comparison is against the previous observation, not an approved baseline.\",\n  \"These are local staged sources, not a live sync of the ChatGPT MHW project.\", \"\",\n  \"## Candidate records\"];\nif (p.report_export_warning) lines.push(\"Export warning: \"+p.report_export_warning, \"\");\nfor (const r of p.records.filter(r => r.kind === \"candidate_record\")) {\n  lines.push(\"### \"+r.name+\" — \"+r.change, \"Source: \"+r.source_path,\n    \"Source status claim: \"+(r.claimed_status || \"unknown\")+\"; current decision: HELD\",\n    ...r.findings.map(f => \"- \"+f.code+\": \"+f.message), \"\");\n}\nlines.push(\"## Next action\", p.next_action);\nreturn [{json:{run_id:p.run_id, observed_at:p.created_at, status:p.status, source_changes:changes,\n  summary:p.summary, publication_allowed:false, report_export_warning:p.report_export_warning || null, review_markdown:lines.join(\"\\n\"),\n  held_items:p.records.map(r=>({id:r.id,name:r.name,change:r.change,source_path:r.source_path,findings:r.findings})),\n  removed_items:p.removed}}];"}},output:[{status:'REVIEW_REQUIRED',publication_allowed:false,review_markdown:'Review changed source records.'}]});
const unchangedReport=node({type:'n8n-nodes-base.code',version:2,config:{name:'Review Unchanged Holds',position:[970,440],parameters:{mode:'runOnceForAllItems',language:'javaScript',jsCode:"const p = $input.first().json;\nconst changes = p.summary.added+p.summary.changed+p.summary.removed;\nconst lines = [\"# Hunter OS source review\", \"\", \"**REVIEW REQUIRED — no publication approved**\", \"\",\n  \"Run: \"+p.run_id, \"Observed: \"+p.created_at, \"\",\n  p.summary.total+\" items: \"+p.summary.candidate_records+\" candidate records and \"+p.summary.forum_sections+\" forum sections.\",\n  \"Added: \"+p.summary.added+\" · Changed: \"+p.summary.changed+\" · Removed: \"+p.summary.removed+\" · Unchanged: \"+p.summary.unchanged,\n  \"Held for review: \"+p.summary.held, \"\",\n  \"Comparison is against the previous observation, not an approved baseline.\",\n  \"These are local staged sources, not a live sync of the ChatGPT MHW project.\", \"\",\n  \"## Candidate records\"];\nif (p.report_export_warning) lines.push(\"Export warning: \"+p.report_export_warning, \"\");\nfor (const r of p.records.filter(r => r.kind === \"candidate_record\")) {\n  lines.push(\"### \"+r.name+\" — \"+r.change, \"Source: \"+r.source_path,\n    \"Source status claim: \"+(r.claimed_status || \"unknown\")+\"; current decision: HELD\",\n    ...r.findings.map(f => \"- \"+f.code+\": \"+f.message), \"\");\n}\nlines.push(\"## Next action\", p.next_action);\nreturn [{json:{run_id:p.run_id, observed_at:p.created_at, status:p.status, source_changes:changes,\n  summary:p.summary, publication_allowed:false, report_export_warning:p.report_export_warning || null, review_markdown:lines.join(\"\\n\"),\n  held_items:p.records.map(r=>({id:r.id,name:r.name,change:r.change,source_path:r.source_path,findings:r.findings})),\n  removed_items:p.removed}}];"}},output:[{status:'REVIEW_REQUIRED',publication_allowed:false,review_markdown:'No source changes; existing holds remain.'}]});
const usageNote=sticky('## Start here\nClick Execute workflow. Open the final Review node and read review_markdown and held_items. A green execution means the review ran, not that records are approved. Failed API or validation calls stop visibly; retry after fixing the cause.',[startReview,compareSources,validatePacket],{color:4});
const futureNote=sticky('## Later: approved data to Discord\nTyped import → source verification → explicit review decision → card rendering → forum update → delivery receipt. These are future steps, not enabled nodes. The MH chat remains directly connected to Animus/Hunter OS.',[hasChanges,changedReport,unchangedReport],{color:3});
export default workflow('hunter-os-source-review','Hunter OS - Source Review')
.add(startReview).to(compareSources).to(validatePacket).to(hasChanges.onTrue(changedReport).onFalse(unchangedReport))
.add(usageNote).add(futureNote);
